title: "Vaibhav Dutt Trivedi's Resume"
email: "trivedivaibhav0111@gmail.com"
description: "A passionate developer's resume."
baseurl: "" # keep this empty if deploying to user.github.io
url: "https://vaibhav-2709.github.io" # ğŸ” Replace with your actual GitHub Pages URL
theme: minima

social_links:
  linkedin: "https://linkedin.com/in/vaibhav-dutt-trivedi-206a19274"
  github: "https://github.com/vaibhav-2709"

# Optional: These help GitHub Pages render your site cleanly
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional but useful:
markdown: kramdown
highlighter: rouge
